# Generated by Django 5.1.1 on 2024-09-17 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Donut', 'Donut'), ('Cheesecake', 'Cheesecake'), ('Cookies', 'Cookies')], default='Donut', max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('topping', models.CharField(blank=True, default='', max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1)),
                ('availability', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
